apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexagate.fullname" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "nexagate.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
